### ISSUE TITLE
Support new keyword: `do`

### ISSUE THREAD

**Issue by wavebeem** [igalic/vim-squiggle#1]
Squiggle has a new keyword, `do`. So far it is always paired with an `end` and denotes a block scope.

Examples:

```
let [x, y] = do
  let z = foo()
  [z, -z]
end
```

```
[1, 2, 3].forEach(fn(x, _, _) do
  let msg = "Item: " .. x
  console.log(msg)
end)
```

**Comment by igalic** [comment]
my plan is to rewrite the matching rules to be nestable.

**Comment by wavebeem** [comment]
Squiggle is dead 💀
